server:
  port: 8082
  servlet:
    context-path: /ordersUdemy

springdoc:
  swagger-ui.path: /swaggerDocs
  api-docs.enabled: true
  swagger-ui.enabled: true

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=ordersMicroservices;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
