server:
  port: 8081
  servlet:
    context-path: /productsUdemy

springdoc:
  swagger-ui.path: /swaggerDocs
  api-docs.enabled: true
  swagger-ui.enabled: true

spring:
  data:
    mongodb:
      database: productsMicroservices
